// One-time import of the COS roster from "JOCOS - DAILY RATE COMPUTATION 2026 2ND.pdf"
// (Attendance Monitoring, 1st half, July 2026). Employee No. is the natural key.
//
// Data-quality notes from the source PDF:
// - #48 "Padunan, Lucky" had a garbled Position Title cell ("RAYMUNDO"); treated
//   "Raymundo" as part of the name and inferred the position title from SG-3 peers
//   in the same office. Verify with HR.
// - #113, #140, #183 show 0.0 days rendered for the period (highlighted in the
//   source) — likely employees who started partway through July. Imported as
//   ACTIVE with no attendance assumptions.
import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";

const adapter = new PrismaBetterSqlite3({ url: process.env.DATABASE_URL ?? "file:./dev.db" });
const prisma = new PrismaClient({ adapter });

const OFFICE = {
  MAYOR_PS: "OFFICE OF THE CITY MAYOR - PS",
  MAYOR_PSIAD: "OFFICE OF THE CITY MAYOR - PSIAD",
  MAYOR_LES: "OFFICE OF THE CITY MAYOR - LES",
  MAYOR_TES: "OFFICE OF THE CITY MAYOR - TES",
  MAYOR_BPLS: "OFFICE OF THE CITY MAYOR - BPLS",
  MAYOR_EMS: "OFFICE OF THE CITY MAYOR - EMS",
  DILG: "ASSIGNED AT DILG",
  DEPED: "ASSIGNED AT DEPED",
  BALAY_SILANGAN: "ASSIGNED AT BALAY SILANGAN",
  LIGA: "ASSIGNED AT LIGA NG MGA BARANGAY",
  ADMINISTRATOR: "OFFICE OF THE CITY ADMINISTRATOR",
  VICE_MAYOR: "OFFICE OF THE CITY VICE MAYOR",
  HRMO: "OFFICE OF THE CITY HRMO",
  CPDC: "OFFICE OF CPDC",
  BUDGET: "OFFICE OF THE CITY BUDGET OFFICER",
  ACCOUNTANT: "OFFICE OF THE CITY ACCOUNTANT",
  GSO: "OFFICE OF THE CITY GSO",
  TREASURER: "OFFICE OF THE CITY TREASURER",
  ASSESSOR: "OFFICE OF THE CITY ASSESSOR",
  CIVIL_REGISTRAR: "OFFICE OF THE CITY CIVIL REGISTRAR",
  HEALTH: "OFFICE OF THE CITY HEALTH OFFICER",
  CSWDO: "OFFICE OF THE CSWDO",
  AGRICULTURIST: "OFFICE OF THE CITY AGRICULTURIST",
  VETERINARIAN: "OFFICE OF THE CITY VETERINARIAN",
  ENGINEER: "OFFICE OF THE CITY ENGINEER",
  BUILDING_OFFICIAL: "OFFICE OF THE CITY BUILDING OFFICIAL",
} as const;

type Row = [employeeNo: string, officeAssignment: string, name: string, positionTitle: string, salaryGrade: number];

const ROSTER: Row[] = [
  ["1", OFFICE.MAYOR_PS, "Dalag, Cristine Joy S.", "Admin. Aide III (Clerk I)", 3],
  ["2", OFFICE.MAYOR_PS, "Domingo, Leslie Anne I.", "Admin. Aide III (Clerk I)", 3],
  ["3", OFFICE.MAYOR_PS, "Erorita, Eric G.", "Admin. Aide III (Driver I)", 3],
  ["4", OFFICE.MAYOR_PS, "Ugot, Spencer B.", "Admin. Aide III (Driver I)", 3],
  ["5", OFFICE.MAYOR_PSIAD, "Agmata, Rayginald John S.", "Admin. Aide IV (Clerk II)", 4],
  ["6", OFFICE.MAYOR_PSIAD, "Agnir, Dennis A.", "Watchman I", 2],
  ["7", OFFICE.MAYOR_PSIAD, "Agustin, Wilfredo A.", "Traffic Aide I", 3],
  ["8", OFFICE.MAYOR_PSIAD, "Alcoy, Brent Phillip M.", "Admin. Aide III (Audio-visual Equipment Operator)", 3],
  ["9", OFFICE.MAYOR_PSIAD, "Lagmay, Angelika N.", "Traffic Aide I", 3],
  ["10", OFFICE.MAYOR_PSIAD, "Laud, Joseph M.", "Watchman I", 2],
  ["11", OFFICE.MAYOR_PSIAD, "Manzano, Robert Jr. S.", "Watchman I", 2],
  ["12", OFFICE.MAYOR_PSIAD, "Real, Demilka Vienna A.", "Nursing Attendant II", 4],
  ["13", OFFICE.MAYOR_PSIAD, "Sagun, Kayla Aloha R.", "Traffic Aide I", 3],
  ["14", OFFICE.MAYOR_PSIAD, "Vives, Keanu Yves B.", "Watchman I", 2],
  ["15", OFFICE.MAYOR_LES, "Mayo, Jesther James B.", "Admin. Aide III (Clerk I)", 3],
  ["16", OFFICE.MAYOR_TES, "Barroga, Kyle Jeremie Will A.", "Admin. Aide III", 3],
  ["17", OFFICE.MAYOR_TES, "Gappi, April Lucky Rhob O.", "Admin. Aide IV (Clerk II)", 4],
  ["18", OFFICE.MAYOR_TES, "Lao-Ang, John Fred T.", "Admin. Aide IV (Clerk II)", 4],
  ["19", OFFICE.MAYOR_TES, "Pagtama, Jack Cyber S.", "Admin. Aide III (Clerk I)", 3],
  ["20", OFFICE.MAYOR_BPLS, "Boquerente, Keith Bryan M.", "Administrative Aide III (Clerk I)", 3],
  ["21", OFFICE.MAYOR_BPLS, "Bumanglag, Khaycee M.", "Administrative Aide III (Clerk I)", 3],
  ["22", OFFICE.MAYOR_BPLS, "Solsoloy, April Joy R.", "Admin. Aide IV (Clerk II)", 4],
  ["26", OFFICE.MAYOR_EMS, "Asuncion, Iverson S.", "Admin. Aide I (Laborer I)", 1],
  ["27", OFFICE.MAYOR_EMS, "Balanay, Elisa L.", "Admin. Aide I (Laborer I)", 1],
  ["28", OFFICE.MAYOR_EMS, "Balanay, Reynald L.", "Admin. Aide I (Laborer I)", 1],
  ["29", OFFICE.MAYOR_EMS, "Barut, Henry S.", "Admin. Aide I (Laborer I)", 1],
  ["30", OFFICE.MAYOR_EMS, "Dela Cruz, Daisy N.", "Administrative Aide III (Clerk I)", 3],
  ["31", OFFICE.MAYOR_EMS, "Garma, Cresencia L.", "Admin. Aide I (Laborer I)", 1],
  ["32", OFFICE.MAYOR_EMS, "Gongora, Loly Jane D.", "Admin. Aide I (Laborer I)", 1],
  ["33", OFFICE.MAYOR_EMS, "Gudoy, Miel Joshua D.", "Admin. Aide IV (Clerk II)", 4],
  ["34", OFFICE.MAYOR_EMS, "Laddit, Darwin S.", "Admin. Aide I (Laborer I)", 1],
  ["35", OFFICE.MAYOR_EMS, "Laddit, Marvin S.", "Admin. Aide I (Laborer I)", 1],
  ["36", OFFICE.MAYOR_EMS, "Rante, Rae John S.", "Engineering Aide", 4],
  ["37", OFFICE.MAYOR_EMS, "Sagun, Delmar F.", "Admin. Aide I (Laborer I)", 1],
  ["38", OFFICE.MAYOR_EMS, "Sagun, Marvelyn D.", "Admin. Aide I (Laborer I)", 1],
  ["39", OFFICE.MAYOR_EMS, "Salileng, Daniel B.", "Admin. Aide I (Laborer I)", 1],
  ["40", OFFICE.MAYOR_EMS, "Salileng, Medy B.", "Admin. Aide I (Laborer I)", 1],
  ["41", OFFICE.MAYOR_EMS, "Salvador, Jennelyn S.", "Admin. Aide I (Laborer I)", 1],
  ["42", OFFICE.MAYOR_EMS, "Aguilar, Allen E.", "Admin. Aide I (Laborer I)", 1],
  ["43", OFFICE.MAYOR_EMS, "Daga, Relfjay T.", "Admin. Aide IV (Clerk II)", 4],
  ["44", OFFICE.MAYOR_EMS, "Dauz, Raymundo L.", "Admin. Aide I (Laborer I)", 1],
  ["45", OFFICE.MAYOR_EMS, "Imbat, Mikka Ariane M.", "Admin. Aide III (Clerk I)", 3],
  ["46", OFFICE.MAYOR_EMS, "Lopez, Apple Mae D.", "Admin. Aide III (Clerk I)", 3],
  ["47", OFFICE.MAYOR_EMS, "Omotoy, Marlon Alexis M.", "Watchman I", 2],
  ["48", OFFICE.MAYOR_EMS, "Padunan, Lucky Raymundo", "Admin. Aide III (Clerk I)", 3],
  ["49", OFFICE.MAYOR_EMS, "Palma, Ericka L.", "Admin. Aide IV (Clerk II)", 4],
  ["50", OFFICE.MAYOR_EMS, "Rocutan, Annebolyn", "Admin. Aide I (Utility Worker I)", 1],
  ["51", OFFICE.MAYOR_EMS, "Balber, Fernando M.", "Admin. Aide I (Utility Worker I)", 1],
  ["52", OFFICE.MAYOR_EMS, "Camangeg, Joemar M.", "Admin. Aide I (Utility Worker I)", 1],
  ["53", OFFICE.MAYOR_EMS, "Castillo, Emily A.", "Admin. Aide I (Utility Worker I)", 1],
  ["54", OFFICE.MAYOR_EMS, "Castro, Alfonso R.", "Admin. Aide I (Utility Worker I)", 1],
  ["55", OFFICE.MAYOR_EMS, "Diric, Cliff Richard S.", "Admin. Aide I (Utility Worker I)", 1],
  ["56", OFFICE.MAYOR_EMS, "Ibuyat, Francisco Jr. B.", "Admin. Aide I (Utility Worker I)", 1],
  ["57", OFFICE.MAYOR_EMS, "Matutino, Arlyn Joy Q.", "Admin. Aide I (Utility Worker I)", 1],
  ["58", OFFICE.MAYOR_EMS, "Palapal, Hencemengie L.", "Admin. Aide I (Utility Worker I)", 1],
  ["59", OFFICE.MAYOR_EMS, "Quemquem, Anielou P.", "Admin. Aide IV (Clerk II)", 4],
  ["60", OFFICE.MAYOR_EMS, "Reyes, Raymund B.", "Admin. Aide II", 2],
  ["61", OFFICE.MAYOR_EMS, "Rocutan, Linder M.", "Admin. Aide I (Utility Worker I)", 1],
  ["62", OFFICE.MAYOR_EMS, "Siading, Jesusa T.", "Admin. Aide I (Utility Worker I)", 1],
  ["63", OFFICE.MAYOR_EMS, "Ugot, Constante A.", "Admin. Aide I (Utility Worker I)", 1],
  ["64", OFFICE.DILG, "de la Cruz, Andrea Mae S.", "Admin. Aide III (Clerk I)", 3],
  ["65", OFFICE.DILG, "Ramos, Carla Joy J.", "Admin. Aide IV (Clerk II)", 4],
  ["66", OFFICE.DEPED, "Agustin, Alden V.", "Watchman I", 2],
  ["67", OFFICE.DEPED, "Caluya, Gilbert D.", "Watchman I", 2],
  ["68", OFFICE.DEPED, "Caraoa, Ruby Allan S.", "Admin. Aide I (Utility Worker I)", 1],
  ["69", OFFICE.DEPED, "Claro, Joy B.", "Admin. Aide I (Utility Worker I)", 1],
  ["70", OFFICE.DEPED, "Culaton, Marjorie L.", "Admin. Aide I (Utility Worker I)", 1],
  ["71", OFFICE.DEPED, "Jose, Rey S.", "Administrative Aide I (Utility Worker I)", 1],
  ["72", OFFICE.DEPED, "Juan, Quirino Jr. B.", "Watchman I", 2],
  ["73", OFFICE.DEPED, "Maduli, Kris Neil T.", "Watchman I", 2],
  ["74", OFFICE.DEPED, "Miranda, John Paul C.", "Watchman I", 2],
  ["75", OFFICE.DEPED, "Puyaoan, Randy G.", "Admin. Aide I (Utility Worker I)", 1],
  ["77", OFFICE.DEPED, "Quimoyog, Dante G.", "Security Guard I", 3],
  ["79", OFFICE.DEPED, "Tabura, George Allan P.", "Admin. Aide I (Utility Worker I)", 1],
  ["80", OFFICE.DEPED, "Torres, Luisito Maria P.", "Admin. Aide I (Utility Worker I)", 1],
  ["81", OFFICE.BALAY_SILANGAN, "Almazan, Karen Mae N.", "Admin. Aide IV (Clerk II)", 4],
  ["82", OFFICE.BALAY_SILANGAN, "Juan, Juvie B.", "Admin. Aide IV (Clerk II)", 4],
  ["83", OFFICE.LIGA, "Lasprillas, Malou M.", "Admin. Aide III (Clerk I)", 3],
  ["85", OFFICE.ADMINISTRATOR, "Rivera, Francis Lorette III G.", "Admin. Aide III (Driver I)", 3],
  ["86", OFFICE.VICE_MAYOR, "Bautista, Lorie Mae C.", "Admin. Aide III (Clerk I)", 3],
  ["87", OFFICE.VICE_MAYOR, "Lagmay, Christopher B.", "Admin. Aide III (Driver I)", 3],
  ["88", OFFICE.VICE_MAYOR, "Pungtilan, Charles Glen B.", "Admin. Aide III (Driver I)", 3],
  ["89", OFFICE.HRMO, "Dipit, Maria Jeneka A.", "Admin. Aide III (Clerk I)", 3],
  ["90", OFFICE.CPDC, "Andres, Richard D.", "Project Development Officer I", 11],
  ["91", OFFICE.CPDC, "Cabasa, Mark Johnley", "Computer Programmer I", 11],
  ["92", OFFICE.CPDC, "Manuel, Arvin Jahn N.", "Zoning Inspector I", 6],
  ["93", OFFICE.CPDC, "Viernes, Lois Heaven B.", "Admin. Assistant I (Computer Operator I)", 7],
  ["94", OFFICE.BUDGET, "Arcangel, Marco Franhill A.", "Admin. Aide III (Clerk I)", 3],
  ["95", OFFICE.BUDGET, "Gampong, Dianne Monette P.", "Admin. Aide III (Clerk I)", 3],
  ["96", OFFICE.BUDGET, "Salileng, Dianne Antonette D.", "Admin. Aide VI (Clerk III)", 6],
  ["97", OFFICE.BUDGET, "Tapon, Shirly G.", "Admin. Aide VI (Clerk III)", 6],
  ["98", OFFICE.ACCOUNTANT, "Clemente, Sophia Gaile N.", "Admin. Aide III (Clerk I)", 3],
  ["99", OFFICE.ACCOUNTANT, "Gaspar, Jameson Carl G.", "Admin. Aide IV (Clerk II)", 4],
  ["100", OFFICE.ACCOUNTANT, "Maligsay, Janssen Loyd C.", "Admin. Aide III (Clerk I)", 3],
  ["101", OFFICE.ACCOUNTANT, "Pagtama, Collene Gayle M.", "Admin. Aide III (Clerk I)", 3],
  ["102", OFFICE.ACCOUNTANT, "Tabuyo, Lyka P.", "Admin. Aide IV (Clerk II)", 4],
  ["103", OFFICE.GSO, "Aguinaldo, Ersyl B.", "Admin. Aide II", 2],
  ["104", OFFICE.GSO, "Aguinaldo, Rodolfo Jr. B.", "Admin. Aide I (Utility Worker I)", 1],
  ["105", OFFICE.GSO, "Agulay, Ervin Nicko J.", "Admin. Aide IV (Electrician I)", 4],
  ["106", OFFICE.GSO, "Alcarion, Mark Christian V.", "Admin. Aide IV (Clerk II)", 4],
  ["107", OFFICE.GSO, "Almazan, John Reighner A.", "Admin. Aide IV (Electrician I)", 4],
  ["108", OFFICE.GSO, "Ancheta, Marjorie E.", "Admin. Aide III (Clerk I)", 3],
  ["109", OFFICE.GSO, "Calacal, Crisanto G.", "Admin. Aide IV (Clerk II)", 4],
  ["110", OFFICE.GSO, "Castillo, Rosemarie C.", "Admin. Aide I (Laborer I)", 1],
  ["111", OFFICE.GSO, "Lagmay, Jessa Bel D.", "Admin. Aide IV (Clerk II)", 4],
  ["112", OFFICE.GSO, "Mabborang, Devorah Q.", "Admin. Aide IV (Clerk II)", 4],
  ["113", OFFICE.GSO, "Malihan, Jay Ven B.", "Admin. Aide I (Utility Worker I)", 1],
  ["114", OFFICE.GSO, "Padulip, Ryan T.", "Admin. Aide I (Utility Worker I)", 1],
  ["115", OFFICE.GSO, "Pambid, Cristel Dianne M.", "Admin. Aide IV (Clerk II)", 4],
  ["116", OFFICE.GSO, "Ranga, Diannahra Ayra", "Admin. Aide IV (Clerk II)", 4],
  ["117", OFFICE.GSO, "Ribac, Eddie Lord B.", "Admin. Aide IV (Electrician I)", 4],
  ["118", OFFICE.GSO, "Rodrigo, Rogelio R.", "Admin. Aide I (Utility Worker I)", 1],
  ["119", OFFICE.GSO, "Salucop, Jefferson C.", "Admin. Aide I (Utility Worker I)", 1],
  ["120", OFFICE.GSO, "Sapaden, Francis Nazer G.", "Admin. Aide VI (Air-conditioning Technician I)", 6],
  ["121", OFFICE.GSO, "Sapaden, Paul Daverick M.", "Admin. Aide IV (Electrician I)", 4],
  ["122", OFFICE.GSO, "Verdadero, Sharina Mae A.", "Admin. Aide III (Clerk I)", 3],
  ["123", OFFICE.TREASURER, "Abitong, Lucky Mark M.", "Admin. Aide III (Clerk I)", 3],
  ["124", OFFICE.TREASURER, "Saguiguit, Jeric E.", "Admin. Aide III (Clerk I)", 3],
  ["125", OFFICE.ASSESSOR, "Orque, Jayson Ver B.", "Admin. Aide III (Clerk I)", 3],
  ["126", OFFICE.ASSESSOR, "Rosini, Lenalyn C.", "Admin. Aide III (Clerk I)", 3],
  ["127", OFFICE.CIVIL_REGISTRAR, "Faderan, Michelle S.", "Admin. Aide IV (Clerk II)", 4],
  ["128", OFFICE.CIVIL_REGISTRAR, "Lagmay, Eloisa Lyne G.", "Admin. Aide IV (Clerk II)", 4],
  ["129", OFFICE.CIVIL_REGISTRAR, "Longgat, Maureen Joy C.", "Admin. Aide IV (Clerk II)", 4],
  ["130", OFFICE.HEALTH, "Abellon, Kirk Devin P.", "Admin. Aide IV (Clerk II)", 4],
  ["131", OFFICE.HEALTH, "Abuy, Eileen Joy U.", "Admin. Aide III (Clerk I)", 3],
  ["132", OFFICE.HEALTH, "Agpaoa, Jonel Q.", "Admin. Aide III (Driver I)", 3],
  ["133", OFFICE.HEALTH, "Aguinaldo, Roxanne Lee T.", "Admin. Aide IV (Clerk II)", 4],
  ["134", OFFICE.HEALTH, "Agulay, Alexander A.", "Watchman II", 2],
  ["135", OFFICE.HEALTH, "Austria, Febie-Rose Q.", "Admin. Aide IV (Clerk II)", 4],
  ["136", OFFICE.HEALTH, "Baga, Edna Jean M.", "Medical Technologist I", 12],
  ["137", OFFICE.HEALTH, "Bajo, Cheryll B.", "Nurse I", 15],
  ["138", OFFICE.HEALTH, "Baldugo, Joel C.", "Admin. Aide III (Driver I)", 3],
  ["139", OFFICE.HEALTH, "Basamot, Jeanalyne A.", "Sanitation Inspector I", 6],
  ["140", OFFICE.HEALTH, "Dela Cruz, Sheena Angela R.", "Medical Technologist I", 12],
  ["141", OFFICE.HEALTH, "Espiritu, Ralph Emerson T.", "Admin. Aide IV (Clerk II)", 4],
  ["142", OFFICE.HEALTH, "Lagmay, Sheer Kevin I.", "Admin. Aide IV (Clerk II)", 4],
  ["143", OFFICE.HEALTH, "Macabiog, Ernesto Uriel A.", "Dentist II", 17],
  ["144", OFFICE.HEALTH, "Maloom, Genevieve A.", "Laboratory Technician I", 6],
  ["145", OFFICE.HEALTH, "Pagay, Sherelyn C.", "Nurse I", 15],
  ["146", OFFICE.HEALTH, "Pungtilan, Alexzandria T.", "Nurse I", 15],
  ["147", OFFICE.HEALTH, "Sagsagat, Pearl Kristine S.", "Admin. Aide IV (Contact Tracer)", 4],
  ["148", OFFICE.HEALTH, "Saludez, Shiela Madonna Sandee B.", "Nurse I", 15],
  ["149", OFFICE.HEALTH, "Tariga, Bret Eros Ivan L.", "Admin. Aide IV (Clerk II)", 4],
  ["150", OFFICE.HEALTH, "Tinio, Duke Benedick R.", "Admin. Aide IV (Clerk II)", 4],
  ["151", OFFICE.HEALTH, "Tolentino, Cheenee Mae U.", "Nursing Attendant II", 6],
  ["152", OFFICE.CSWDO, "Sipisip, Paul John L.", "Admin. Aide I (Laborer I)", 1],
  ["153", OFFICE.CSWDO, "Almazan, Eugenio Jr. C.", "Admin. Aide III (Driver I)", 3],
  ["154", OFFICE.CSWDO, "Bagay, Edlhen Mae D.", "Admin. Aide III (Clerk I)", 3],
  ["155", OFFICE.CSWDO, "Basamot, Jeraldine Q.", "Admin. Aide III (Clerk I)", 3],
  ["156", OFFICE.CSWDO, "Dancel, Joseph Sr. G.", "Admin. Aide I (Utility Worker I)", 1],
  ["157", OFFICE.CSWDO, "Dela Rosa, Zeny L.", "Admin. Aide I (Utility Worker I)", 1],
  ["158", OFFICE.CSWDO, "Mataya, Generose B.", "Admin. Aide III (Clerk I)", 3],
  ["159", OFFICE.CSWDO, "Reantillo, Catherine U.", "Admin. Aide III (Clerk I)", 3],
  ["160", OFFICE.CSWDO, "Sapaden, Mica Shegella A.", "Social Welfare Aide", 4],
  ["161", OFFICE.CSWDO, "Silac, John Paul", "Admin. Aide IV (Clerk II)", 4],
  ["162", OFFICE.AGRICULTURIST, "Aspili, Maydee P.", "Admin. Aide I (Laborer I)", 1],
  ["163", OFFICE.AGRICULTURIST, "Basamot, Angelbert I.", "Admin. Aide I (Laborer I)", 1],
  ["164", OFFICE.AGRICULTURIST, "Bataan, Rajah King III P.", "Admin. Aide I (Laborer I)", 1],
  ["165", OFFICE.AGRICULTURIST, "Clemente, Lord Patrick A.", "Admin. Aide I (Laborer I)", 1],
  ["166", OFFICE.AGRICULTURIST, "Espiritu, Reynaldo S.", "Admin. Aide I (Laborer I)", 1],
  ["167", OFFICE.AGRICULTURIST, "Francisco, Rely S.", "Admin. Aide I (Laborer I)", 1],
  ["168", OFFICE.AGRICULTURIST, "Galimba, Michael B.", "Heavy Equipment Operator I", 4],
  ["169", OFFICE.AGRICULTURIST, "Galimba, Rodel B.", "Heavy Equipment Operator I", 4],
  ["170", OFFICE.AGRICULTURIST, "Gappi, Harley I.", "Heavy Equipment Operator I", 4],
  ["171", OFFICE.AGRICULTURIST, "Gappi, James Bryan I.", "Admin. Aide I (Laborer I)", 1],
  ["172", OFFICE.AGRICULTURIST, "Gappi, Mark Alvin G.", "Admin. Aide I (Laborer I)", 1],
  ["173", OFFICE.AGRICULTURIST, "Godoy, Jonathan Sr. S.", "Admin. Aide I (Laborer I)", 1],
  ["174", OFFICE.AGRICULTURIST, "Ibuyat, Godfrey E.", "Admin. Aide I (Laborer I)", 1],
  ["175", OFFICE.AGRICULTURIST, "Masian, Melvin", "Admin. Aide I (Laborer I)", 1],
  ["176", OFFICE.AGRICULTURIST, "Masian, Sherwin A.", "Admin. Aide I (Laborer I)", 1],
  ["177", OFFICE.AGRICULTURIST, "Pacunayen, Ricardo P.", "Admin. Aide I (Laborer I)", 1],
  ["178", OFFICE.AGRICULTURIST, "Pungtilan, John Niño B.", "Admin. Aide I (Laborer I)", 1],
  ["179", OFFICE.AGRICULTURIST, "Rivera, Dembert B.", "Heavy Equipment Operator I", 4],
  ["180", OFFICE.AGRICULTURIST, "Sagun, Kenneth D.", "Admin. Aide I (Laborer I)", 1],
  ["181", OFFICE.AGRICULTURIST, "Salut, Wendell G.", "Admin. Aide I (Laborer I)", 1],
  ["182", OFFICE.VETERINARIAN, "Espiritu, Rachel S.", "Livestock Inspector II", 8],
  ["183", OFFICE.VETERINARIAN, "Barroga, Erwin Sr. C.", "Admin. Aide I (Utility Worker I)", 1],
  ["184", OFFICE.VETERINARIAN, "Castillo, Daryll Wilfred M.", "Admin. Aide I (Utility Worker I)", 1],
  ["185", OFFICE.VETERINARIAN, "Manegdeg, Mica Ricci D.", "Livestock Inspector I", 6],
  ["186", OFFICE.VETERINARIAN, "Pungtilan, Kristine N.", "Meat Inspector I", 6],
  ["187", OFFICE.VETERINARIAN, "Ranes, Edhelbert G.", "Admin. Aide I (Utility Worker I)", 1],
  ["188", OFFICE.ENGINEER, "Bucalig, Christian Jay T.", "Engineer I", 12],
  ["189", OFFICE.ENGINEER, "Camangeg, Abelardo F.", "Heavy Equipment Operator I", 4],
  ["190", OFFICE.ENGINEER, "Camangeg, Edrian O.", "Draftsman I", 6],
  ["191", OFFICE.ENGINEER, "Castillo-Flojo, Stephanie Mia T.", "Engineer I", 12],
  ["192", OFFICE.ENGINEER, "Icuspit, Alyssa Joy O.", "Project Development Officer I", 11],
  ["193", OFFICE.ENGINEER, "Mapugay, Jerald Paolo R.", "Engineer I", 12],
  ["194", OFFICE.ENGINEER, "Paguibitan, Rocky G.", "Admin. Aide I (Laborer I)", 1],
  ["195", OFFICE.ENGINEER, "Peralta, Reynaldo U.", "Admin. Aide I (Laborer I)", 1],
  ["196", OFFICE.ENGINEER, "Tabili, Pauline P.", "Engineer I", 12],
  ["197", OFFICE.BUILDING_OFFICIAL, "Morales, Novie Jay A.", "Engineer I (Mechanical Engineer)", 12],
  ["198", OFFICE.BUILDING_OFFICIAL, "Pablo, Ahcsell N.", "Engineer I (Civil Engineer)", 12],
  ["199", OFFICE.BUILDING_OFFICIAL, "Pacunayen, Shaira Jamaica S.", "Admin. Aide IV (Clerk II)", 4],
  ["200", OFFICE.BUILDING_OFFICIAL, "Quicquic, Randel P.", "Admin. Aide IV (Clerk II)", 4],
  ["201", OFFICE.BUILDING_OFFICIAL, "Suagao, Jessa Mae V.", "Admin. Aide IV (Clerk II)", 4],
  ["202", OFFICE.BUILDING_OFFICIAL, "Talaro, Angelou A.", "Admin. Aide IV (Clerk II)", 4],
];

async function main() {
  let created = 0;
  let updated = 0;

  for (const [employeeNo, officeAssignment, name, positionTitle, salaryGrade] of ROSTER) {
    const existing = await prisma.employee.findUnique({ where: { employeeNo } });
    await prisma.employee.upsert({
      where: { employeeNo },
      update: { officeAssignment, name, positionTitle, salaryGrade },
      create: { employeeNo, officeAssignment, name, positionTitle, salaryGrade, status: "ACTIVE" },
    });
    if (existing) updated++;
    else created++;
  }

  console.log(`Roster import complete: ${created} created, ${updated} updated, ${ROSTER.length} total.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
